image: node:16-alpine

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - install
  - build
  - test
  - quality
  - deploy


install:
  stage: install
  cache:
    key: $CI_COMMIT_REF_SLUG 
    paths:
      - .npm/
  script:
    - npm ci --cache .npm --prefer-offline

build:
  stage: build
  cache:
    key: $CI_COMMIT_REF_SLUG 
    paths:
      - node_modules/
    policy: pull
  script:
    - npm run build
  artifacts:
    paths:
      - build/

test:
  stage: test
  needs:
    - build
  cache:
    key: $CI_COMMIT_REF_SLUG 
    paths:
      - node_modules/
    policy: pull
  script:
    - npm test -- --coverage --watchAll=false --detectOpenHandles --forceExit --ci
  artifacts:
    paths:
      - coverage/
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

code_quality:
  stage: test
  needs:
    - build
  artifacts:
    expose_as: 'Code Quality Report'
    paths: [gl-code-quality-report.json]
    expire_in: 10 days

code_quality_html:
  stage: test
  extends: code_quality
  variables:
    REPORT_FORMAT: html
  artifacts:
    expose_as: 'Code Quality Report HTML'
    paths: [gl-code-quality-report.html]
    expire_in: 10 days

sonarqube:
  stage: quality
  needs:
    - test
  image:
    name: sonarsource/sonar-scanner-cli:4.6
    entrypoint: [ "" ]
  script:
    - sonar-scanner -Dsonar.login=$SONAR_LOGIN -Dsonar.projectKey=$SONAR_PROJECT_KEY
  dependencies:
    - test


staging:
  stage: deploy
  needs:
    - build
    - test
  environment:
    name: staging
  before_script:
    - npm install -g firebase-tools
  script:
    - firebase deploy --token $FIREBASE_TOKEN -P $STAGING_ID
  dependencies:
    - build
  only:
    - staging

production:
  stage: deploy
  needs:
    - build
    - test
  environment:
    name: production
  before_script:
    - npm install -g firebase-tools
  script:
    - firebase deploy --token $FIREBASE_TOKEN -P $PROD
